anchore/scan-action

dist/index.js
index.js
lib/run_scan
tests/fixtures/content-merge.fixture.json
tests/index.test.js

Will always return all package types not just os pkgs in content.json

merge bill of materials into a single content.json

---

dist/index.js
index.js
package-lock.json
package.json
tests/index.test.js

Use @actions/exec

---

README.md

Signed-off-by: Zach Hill <zach@anchore.com>

Add anchore-version to README

---

dist/index.js
index.js

fixes #22 
Signed-off-by: Brady Todhunter <bradyt@anchore.com>

check if failBuild is set specifically to true, not just a value

---

.github/workflows/sarifdemo.yml
README.md
action.yml
dist/index.js
index.js
tests/index.test.js

Adds optional parameters to enable integration with GitHub Code Scanning feature.  When enabled, the anchore scan action generates a sarif formatted result that can then be uploaded via the code scanning action.

GitHub Code Scanning Integration

---

README.md

* use improved actions/checkout@v2 action for faster checkouts

actions/checkout@v2 instead of actions/checkout@v1

---

README.md

Signed-off-by: Brady Todhunter <bradyt@anchore.com>

use @v1 in README as per GitHub actions best practices

---

dist/index.js
index.js
package-lock.json
package.json

Signed-off-by: Robert Prince <robert.prince@anchore.com>
Co-authored-by: Brady Todhunter <bradyt@anchore.com>

Update to Anchore Engine version 0.7.3

---

dist/index.js
index.js

Signed-off-by: Robert Prince <robert.prince@anchore.com>

Update to Anchore inline_scan/Engine v0.8.0

---

dist/index.js
index.js

Signed-off-by: Robert Prince <robert.prince@anchore.com>

Update to Anchore inline_scan 0.8.1

---

action.yml
dist/index.js
index.js

Match the outputs in `action.yml`

ensure vulnerabilities output matches the action

---

CHANGELOG.md
dist/index.js

Minor verbiage changes to the changelog.

changelog: update verbiage

---

dist/index.js
index.js

Closes https://github.com/anchore/scan-action/issues/74

bump grype to 0.5.0

---

dist/index.js
index.js

Fixes https://github.com/anchore/scan-action/issues/80

bump grype to 0.7.0

---

Makefile
README.md
scripts/local.sh
tests/fixtures/localbuild/Dockerfile
workflows/image.yml

The documentation mentioned what the simplest check would be with a local build. But with Github Actions it is kind of tricky to get right, so this PR updates the docs and includes a functional test that makes sure the the example works.
Closes #85

Document examples of creating a localbuild 

---

dist/index.js
index.js
tests/__snapshots__/sarif_output.test.js.snap

Bump Grype to the latest release.

Update Grype to 0.27.3

---

dist/index.js
index.js
tests/__snapshots__/sarif_output.test.js.snap
tests/sarif_output.test.js

Minor issue with SARIF output from Grype, fixed in 0.34.4

Update Grype to 0.34.4

---

action.yml
download-grype/action.yml
package-lock.json

#175 showed that our node version was EOL. This PR attempts to update the action to node v16 along with the dependencies in `package.json`
Signed-off-by: Christopher Phillips <christopher.phillips@anchore.com>

update node versions to v16 from v12

---

.github/workflows/test.yml
.husky/pre-commit
dist/index.js
package.json

The `husky` pre-commit hook was not being run after upgrading to v7, this PR corrects that omission. Additionally, it adds a PR workflow validation to ensure the built action is correct.

Update ncc build commit hook and add PR gate to ensure in sync

---

.github/release-drafter.yml

Very small PR to add brackets `[]` around usernames in the changelog template

Update changelog template to surround username with brackets

---

dist/index.js
package-lock.json
package.json
tests/__snapshots__/sarif_output.test.js.snap

This PR adds an `update-deps` script, and runs it to update dependencies to the latest versions.
Fixes: #199

Add update-deps script and also update dependencies

---

.gitignore
README.md
action.yml
dist/index.js
index.js
tests/grype_command.test.js
tests/sarif_output.test.js

Adds support for `--only-fixed` flag
Closes #133

Add only-fixed option

---

.github/workflows/update-grype-release.yml

This PR just updates the automated PR workflow to use conventional commit messages

chore: tweak some workflow text

---

.github/workflows/update-grype-release.yml
package-lock.json
package.json

Update deprecated `::set-output` calls

chore: update deprecated set-output call

---

README.md

chore(docs): update docker related actions to avoid warnings in workflow
