- README.md
I was following the examples in the README for my own repository and noticed that the preview for my Dockerfile did not render properly when I referred to it with a leasing "./"
In the moment I changed the `dockerfile-path` to "Dockerfile" the preview started to render properly:
> Reference Dockerfile without leading ./ to have proper preview rendering

- .github/workflows/demo.yml
- .github/workflows/sarifdemo.yml
- .github/workflows/test.yml
- README.md
This PR updates the workflows to use the latest `actions/checkout@v2` code and updates the README workflow examples to point to a specific tag.
This Pull Request introduces the following two changes:
- Following up on #34 by updating the `.github/workflows` on this repository to the latest `actions/checkout@v2` code
- Updates the `README` workflow examples to point to the latest tagged version of `anchore/scan-action@v1.0.6` instead of `master`.
- GitHub [recommends](https://help.github.com/en/actions/reference/workflow-syntax-for-github-actions#jobsjob_idstepsuses) you use a specific commit target in your workflows instead of `master` so you can ensure compatibility with your workflows, i.e. referencing `@master` means I always have the latest code instead of testing/verifying that …
> Update action workflow versions

- README.md
- action.yml
- index.js
The inputs include-app-packages and debug were not handled correctly. If include-app-packages was set to false, then the slim image version wasn't used.
I also set the default values in the action.yml, because for me it was somehow confusing that there are defaults mentioned in the README, but they were not explicit defined in most cases.
> Fix handling of include-app-packages and debug input

- dist/index.js
- index.js
Currently in the SARIF output of the Action it's possible to have results included who's `ruleId` does not match any rule in the list of rules. This is because rules are de-duplcated on the vulnerability ID, but the rule ID also includes information about the artifact. This means only one rule gets created for all these IDs:
> ANCHOREVULN_CVE-2004-0971_deb_krb5-multidev_1.12.1+dfsg-19+deb8u4
> ANCHOREVULN_CVE-2004-0971_deb_libgssapi-krb5-2_1.12.1+dfsg-19+deb8u4
> ANCHOREVULN_CVE-2004-0971_deb_libgssrpc4_1.12.1+dfsg-19+deb8u4
> ANCHOREVULN_CVE-2004-0971_deb_libk5crypto3_1.12.1+dfsg-19+deb8u4
> ANCHOREVULN_CVE-2004-0971_deb_libkadm5clnt-mit9_1.12.1+dfsg-19+deb8u4
> ANCHOREVULN_CVE-2004-0971_deb_libkadm5srv-mit9_1.12.1+dfsg-19+deb8u4
> …
> Fix overzealous rule deduplication in SARIF output.

- .github/workflows/sarifdemo.yml
- README.md
- action.yml
- dist/index.js
- index.js
This creates a new output called `sarif` for the location of the sarif file.  This will if the file name or location were to change due to the environment of the Action. If users only refer to the file as an output from your action the location string can change without their knowing.
With this change CI configuration looks like this:
```yaml
name: Container Image CI
on: [push]
jobs:
build:
runs-on: ubuntu-latest
steps:
- uses: actions/checkout@v2
- name: Build the Container image
run: docker build . --file Dockerfile --tag localbuild/testimage:latest
- uses: anchore/scan-action@v2
id: scan
with:
image: "localbuild/testimage:latest"
acs-report-enable: true
- name: upload Anchore scan SARIF report
uses: github/codeql-action/upload-sarif@v1
with:
sarif_file: ${{ steps.scan.outputs.sarif }} …
```
> Output the sarif file location

- dist/index.js
- index.js
Example output with the fix:
```
|           "ruleId": "ANCHOREVULN_CVE-2016-2779_deb_libsmartcols1_2.25.2-6",
|           "ruleIndex": 0,
|           "level": "error",
|           "message": {
|             "text": "The container image contains software with a vulnerability: (libsmartcols1 type=deb)",
|             "id": "default"
|           },
```
Not sure why the compiled `index.js` now has a ton of changes :/
> fix undefined items message when scanning containers

- dist/index.js
- index.js
Closes https://github.com/anchore/scan-action/issues/68
/cc @jonico
> guard against the possibility of no links being provided

- dist/index.js
The usage of `core.addPath` was causing the creation of `add-path` into the `dist/index.js` binary via `ncc`. By removing `core.addPath` there are no more warnings. The path is now used directly via the cache instead of just `grype`.
Closes #71
> remove usage of 'core.addPath'

- .github/workflows/test.yml
- .gitignore
- Makefile
- dist/index.js
- index.js
- package-lock.json
- scripts/local.sh
- tests/functional/test_images.py
- tests/functional/test_invalid_input.py
- workflows/tests.yml
Closes https://github.com/anchore/scan-action/issues/67
* Prevents execution from continuing when invalid input is given
* Prevents execution from continuing when no input (neither path or image) is given
* Adds a Makefile with targets for functional testing with `act`
* Adds a test harness to validate output and functional tests of the actions
* Adds a github action validation for PRs that calls `make check` which in turn runs all the new test harness
> Halt execution when invalid options are provided

- dist/index.js
- index.js
Bumping to the latest grype (`0.6.1`) pulls in a version of syft that addresses issue #78 
Fixes #78
> bump grype to 0.6.1

- dist/index.js
- index.js
> respect verbosity from action to call grype

- .github/workflows/demo.yml
- .github/workflows/sarifdemo.yml
- README.md
- action.yml
- tests/functional/test_images.py
- workflows/tests.yml
> change default behavior so action fails on medium (and higher) severities

- dist/index.js
- index.js
This pr addresses most of the items in issue #90 : 
* Changes the title to be as readable as possible
* Changes the sub-title to not be the same as the title, providing context. If the vulnerability has a description, that is provided as the sub-title. Otherwise a text is generated explaining the version affected and additionally if there is a fix for it or not
* The extra context gets reworded depending on analysis of a path or a container
* The container is now included as part of the rule ID so that it can get filtered.
* Removes dead code
Notable omissions from the original issue that this PR does not fix:
* Does not link back files/paths in the container for a reported vulnerability to files in the container
* Does not always populate the severity description from the CVE because …
> Improve SARIF reporting

- .github/workflows/tag-release.yml
Allows to automatically re-tag to a major release (e.g. `v2`) when a new release is done. This saves us from having to do this manually - which is error prone
Closes #40
> github: automatically re-tag a major version release

- .github/workflows/test.yml
- .gitignore
- .jest/setEnvVars.js
- README.md
- dist/index.js
- index.js
- jest.config.js
- package-lock.json
- package.json
- tests/__snapshots__/sarif_output.test.js.snap
Download and use a static Grype database for snapshot testing. This started out because I missed some documentation referencing `v2` release instead of `v3` and had failed tests, so went down a bit of a rabbit hole making the tests reproducible and easier to understand by reverting back to the normal Jest reporter and removing the mountains of Grype output dumped to the logs.
> Pin Grype db for tests #120

- dist/index.js
- index.js
This fixes #132 -- `.grype.yaml` is actually being used for everything except output format (which explicitly set and must be `json` in order for GitHub SARIF vulnerability reporting to work). This outputs the stderr to the logs, which will output the configuration, including the configuration file being used.
> Output Grype stderr to action logs

- GrypeVersion.js
- README.md
- dist/index.js
- download-grype/action.yml
- grype/action.yml
- index.js
- jest.config.js
- tests/action.test.js
- tests/index.test.js
This PR adds a sub-action to download grype, along with some misc. code clean up that was discovered while working on this:
* functions included in the compiled action code which were only being used by tests
* split grype version to a separate file in preparation for adding an auto-updating job in a follow-on PR
An example run is: https://github.com/kzantow-anchore/scan-action-test/runs/5739124385?check_suite_focus=true#step:5:12
With an execution of the Grype binary: https://github.com/kzantow-anchore/scan-action-test/runs/5739124385?check_suite_focus=true#step:7:1
> Add sub-action to download Grype

- .github/workflows/update-grype-release.yml
To help keep the pinned version of Grype up to date, we want a workflow to handle this for us so we know if tests start failing or we can just update with no problem. This PR adds a nightly workflow that checks to see if a new Grype has been released and creates or updates a PR with the corresponding update, including tests.
This fixes #147
> Add auto-PR creator to keep pinned Grype up to date

- .github/workflows/update-grype-release.yml
Ths PR updates the secret names due to moving to organization secrets for the automatic PR when grype is released.
> Update grype release check secret names

- .github/workflows/update-grype-release.yml
The auto-updater job was incorrectly referencing a `.ts` instead of a `.js` file.
> Correct Grype auto-updater

- .github/workflows/update-grype-release.yml
- package-lock.json
- package.json
- tests/index.test.js
`npm install` resulted in 6 moderate vulnerabilities, this incorporates an `npm audit fix` as well as upgrading husky to the more recent version, which requires adding a `.husky/pre-commit` script. This aligns some of the patterns with the `sbom-action` and removes some unused test code as well as correcting another issue with the grype update job.
> Update husky and npm audit fix

- .github/workflows/update-grype-release.yml
For some unknown reason the `npm install` for the automatic grype PR does not appear to be installing the husky hooks; we can workaround this by explicitly running `npm run build`.
> Explicitly run `npm run build` for auto-update PR

- .github/release-drafter.yml
Syft and Grype have an author in the release notes automatically, we should add that to the release drafter template here, too.
See release-drafter docs: https://github.com/marketplace/actions/release-drafter#change-template-variables
> Add author to the release drafter template

- .github/workflows/sarifdemo.yml
- README.md
As is with v1, you get the following warning on an Actions run:
> `CodeQL Action v1 will be deprecated on December 7th, 2022.
> Please upgrade to v2.
> For more information, see https://github.blog/changelog/2022-04-27-code-scanning-deprecation-of-codeql-action-v1/`
Signed-off-by: Steven Maude <git@stevenmaude.co.uk>
> Update CodeQL Action in example to v2

- README.md
- dist/index.js
> Add json format output option

- action.yml
- dist/index.js
- index.js
- tests/grype_command.test.js
- tests/sarif_output.test.js
This fixes issue #186.
The PR #184 missed out on updating the `action.yml` to describe the new input parameter and output field for the action.
Secondly, in that PR only the `./dist/index.js` file was updated with the new feature, but the source file `./index.js` was left untouched. Any subsequent run and commit of `npm run build` would have erased the changes.
I've moved the new code into `./index.js` and regenerated `./dist/index.js`. That also looks to have picked up a few changes due to library updates that had not been integrated into the `dist` output yet.
Finally I've updated a few tests to make them work properly with the new feature.
> Allow input parameter `output-format` and output `report` to be used

- .github/workflows/sarifdemo.yml
- README.md
- action.yml
- dist/index.js
- index.js
- tests/action_args.test.js
- tests/grype_command.test.js
- tests/sarif_output.test.js
This PR is a follow up to #187 which renames the json output file to more closely align to the `output-format` option of `json` or `sarif`, as well as removing the `acs-report-enable` flag, which is no longer necessary.
NOTE: this is not really a breaking change, as the defaults of `output-format=sarif` and `acs-report-enable=true` will result in the same behavior.
> Update output-format and acs-report-enable disconnect

- dist/index.js
- index.js
- package.json
- tests/action_args.test.js
Adds the current process environment variables to the grype process. Useful for proxy variables.
Might fix https://github.com/anchore/scan-action/issues/197
> Include process environment into grype execution

- .github/workflows/tag-release.yml
Updates `actions-tagger` action to remove `GITHUB_TOKEN` environment variable.
> chore: update actions-tagger

- README.md
- action.yml
- dist/index.js
- index.js
- tests/action_args.test.js
- tests/grype_command.test.js
- tests/sarif_output.test.js
Fixes #215 by adding another action input that toggles whether the `--add-cpes-if-none` flag is added to the grype command arguments.
There are some local test failures but these seems to be caused by a missing OCI registry on localhost:5000 which I did not have. I've tested this change just now in https://github.com/metio/devcontainers/commit/bbb47b0aca4ff5fdd4bdec5d64d1649e071bc866 and can see the correct results in an action run, e.g. at https://github.com/metio/devcontainers/actions/runs/4445318515/jobs/7804325686 (job name is "Scan Image with Grype")
> add action input for --add-cpes-if-none flag

- dist/index.js
- index.js
- tests/action_args.test.js
Set the `json` Action output instead of `report` to match what the [documentation](https://github.com/anchore/scan-action/blob/main/README.md?plain=1#L139) describes.
> Set json output

- .github/workflows/test.yml
- .github/workflows/update-grype-release.yml
- .nsprc
- README.md
- action.yml
- dist/index.js
- index.js
- package-lock.json
- package.json
- tests/grype_command.test.js
- tests/sarif_output.test.js
Add an option to allow 'by-cve' output. This is useful for correlating between grype output and other tools that tend to favor CVE.
> Add by-cve option

- dist/index.js
- package-lock.json
While updating the action with a new grype version npm run audit fails because of an issue with semver being vulnerable. https://github.com/anchore/scan-action/actions/runs/6479148648/job/17592137397?pr=236
The upgrade of semver is also failing, so the action is stuck with an old grype version.
This commit has an upgraded semver version and a recreated index.js
> fix: updated semver version

- .github/workflows/test.yml
I've seen some flakiness / surprises with this workflow, and so would like to be able to trigger it directly on `main` to see if it's misbehaving there as well.
> chore: add manual trigger to test workflow

- .github/workflows/test.yml
- tests/action_args.test.js
- tests/grype_command.test.js
- tests/index.test.js
- tests/sarif_output.test.js
There seem to be a few things happening:
1. We sometimes hit jest timeouts. 
2. We sometimes hit `spawn ETXTBSY` from Node, which means that we tried to exec a file that is also open for writing. I think this is a race condition where one test is running grype while another is installing it.
3. We sometimes have an error like: couldn't exec `grype`: is the filename correct and the file marked as executable? (Like this: https://github.com/anchore/scan-action/actions/runs/6931060595/job/18851984035#step:8:144). I think this is also a race WRT to installing grype.
Therefore:
- bump jest timeout from 30s to 90s. Downloading grype and grype DB can take some time, so this seems reasonable
- Install grype in a `beforeAll`, so that when the individual tests run grype, it's already there, so …
> chore: address test flakes

- .github/workflows/demo.yml
- .github/workflows/release-drafter.yml
- .github/workflows/sarifdemo.yml
- .github/workflows/tag-release.yml
- .github/workflows/test.yml
- .github/workflows/update-grype-release.yml
- README.md
This upgrades all GH actions we use to the latest version, and pins them to a commit SHA.
> chore: upgrade and pin all GH actions

- README.md
- action.yml
- dist/index.js
- index.js
- tests/action_args.test.js
- tests/grype_command.test.js
Functionality to implement VEX support in the GitHub action as described in https://github.com/anchore/scan-action/issues/253 
I have added a test and run the existing tests - all tests pass.
I haven't modified all tests to take this argument because I didn't see the benefit, but if there are specific tests beyond the ones that I've added/changed that would help, let me know and I will add them.
> Add support for the `--vex` flag

- .github/workflows/dependabot-auto-merge.yaml
If a dependabot PR bumps a patch or minor version, and tests are green, just merge it. This reduces toil for maintainers.
Workflow file is from anchore/quill/.github/workflows. See anchore/quill#220 and anchore/quill#221.
Note that I had to retry one test job due to a timeout, but it passed on the first retry and seems unrelated.
> chore: auotmatically merge dependabot PRs

- .husky/pre-commit
- package-lock.json
- package.json
pretty-quick was broken by version 3 of prettier in July, but has had no update. Switch to using lint-staged as the runner to lint staged changes based on the docs at https://prettier.io/docs/en/precommit.html. See also https://github.com/azz/pretty-quick/issues/164 and https://stackoverflow.com/a/76628485.
Previously, the pre-commit hook would fail with:
```
TypeError: _prettier.resolveConfig.sync is not a function
at /home/runner/work/scan-action/scan-action/node_modules/pretty-quick/dist/isSupportedExtension.js:12:30
at Array.filter (<anonymous>)
at _default (/home/runner/work/scan-action/scan-action/node_modules/pretty-quick/dist/index.js:53:157)
at Object.<anonymous> (/home/runner/work/scan-action/scan-action/node_modules/pretty-quick/bin/pretty-quick.js:17:27)
```
(for example at …
> chore: switch from pretty-quick to lint-staged

- dist/index.js
- index.js
GitHub Actions windows runners currently have a version of curl that doesn't work with the install.sh script in the grype repo. At least temporarily, just download and extract the grype executable directly from the GH release page.
> fix: download Grype directly on Windows

- README.md
This updates the links to the community Slack to Discourse links, and fixes the incorrect license badge name.
> Update slack to discourse

- README.md
Currently with v2, you get the following warning on an Action run:
`Warning: CodeQL Action v2 will be deprecated on December 5th, 2024. Please update all occurrences of the CodeQL Action in your workflow files to v3. For more information, see https://github.blog/changelog/2024-01-12-code-scanning-deprecation-of-codeql-action-v2/ 
`
>Users of the above-mentioned platforms should update their CodeQL workflow file(s) to refer to the new v3 version of the CodeQL Action.
Signed-off-by: Christof Renner [christof.renner@zeroday.network](mailto:christof.renner@zeroday.network)
> Adjust upload-sarif version to v3

- .github/release-drafter.yml
This PR adjusts the release drafter to exclude dev dependencies.
> chore: exclude dev-deps from release drafter

- README.md
Fix issue with missing permissions directive in example workflow
Per the docs here:
https://docs.github.com/en/code-security/code-scanning/integrating-with-code-scanning/uploading-a-sarif-file-to-github#example-workflow-for-sarif-files-generated-outside-of-a-repository
The permissions section is required for the SARIF upload sub-action to
work correctly.
> Missing perms for cql sarif upld

- .github/workflows/test.yml
- dist/index.js
- package-lock.json
- package.json
This PR removes the `npm audit` step, which causes builds to fail without changes when vulnerabilities are reported. We are already relying on dependabot to update dependencies, we don't need to fail the build.
> chore: remove npm audit from workflow and update deps
